baseURL = "http://dodolalorc.cn/"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"


# 默认每页列表显示的文章数目
paginate = 12
# 谷歌分析代号 [UA-XXXXXXXX-X]
googleAnalytics = "G-4XWE9N9JQK"
# 版权描述，仅仅用于 SEO
copyright = "dodola"

# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 git 信息
enableGitInfo = false
# 是否使用 emoji 代码
enableEmoji = true

# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]


defaultContentLanguage = "zh-cn"

[frontmatter]
lastmod = [":fileModTime", "lastmod"]
# 中文菜单配置
[languages]
[languages.zh-cn]
weight = 1
title = "Doごみ箱🪄"
languageName = "简体中文"
languageCode = "zh-CN"
hasCJKLanguage = true
[[languages.zh-cn.menu.main]]
weight = 1
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = "🐙"
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "文章"
url = "/posts"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
[[languages.zh-cn.menu.main]]
weight = 2
identifier = "series"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = "🌠"
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "系列"
url = "/series/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
[[languages.zh-cn.menu.main]]
weight = 3
identifier = "categories"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = "📂"
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "分类"
url = "/categories/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
[[languages.zh-cn.menu.main]]
weight = 4
identifier = "tags"
pre = "🏷︎"
post = ""
name = "标签"
url = "/tags/"
title = ""
[[languages.zh-cn.menu.main]]
weight = 5
identifier = "links"
pre = "🧸"
post = ""
name = "友链"
url = "/links/"
title = ""
[[languages.zh-cn.menu.main]]
weight = 6
identifier = "about"
pre = '🍅'
post = ""
name = "关于"
url = "/about/"
title = ""
[[languages.zh-cn.menu.main]]
weight = 7
identifier = "comments"
pre = '<i class="fa-solid fa-comment" style="color: #63E6BE;"></i>'
# pre = '🪗'
post = ""
name = "留言"
url = "/comments/"
title = ""

# [languages.en]
#   weight = 2
#   title = "Doごみ箱"
#   languageName = "English"
#   languageCode = "en"
#   hasCJKLanguage = true
#   [[languages.en.menu.main]]
#     weight = 1
#     identifier = "posts"
#     # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
#     pre = "📂"
#     # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
#     post = ""
#     name = "Posts"
#     url = "/posts"
#     # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
#     title = ""
#   [[languages.en.menu.main]]
#     weight = 2
#     identifier = "tags"
#     pre = "🏷︎"
#     post = ""
#     name = "Tags"
#     url = "/tags/"
#     title = ""
#   [[languages.en.menu.main]]
#     weight = 3
#     identifier = "links"
#     pre = "🧸"
#     post = ""
#     name = "Links"
#     url = "/links/"
#     title = ""
#   [[languages.en.menu.main]]
#     weight = 4
#     identifier = "about"
#     pre = '🍅'
#     post = ""
#     name = "About"
#     url = "/about/"
#     title = ""
#   [[languages.en.menu.main]]
#     weight = 5
#     identifier = "comment"
#     pre = '<i class="fa-solid fa-comment" style="color: #63E6BE;"></i>'
#     post = ""
#     name = "Comment"
#     url = "/comments/"
#     title = ""

[params]
version = "0.4.0"
# 网站默认主题样式 ["auto", "light", "dark"]
defaultTheme = "auto"
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
gitRepo = "https://github.com/Florae006/Florae006.github.io.git"
#  哪种哈希函数用来 SRI, 为空时表示不使用 SRI
# ["sha256", "sha384", "sha512", "md5"]
fingerprint = ""
#  日期格式
dateFormat = "2006-01-02"
# 网站标题, 用于 Open Graph 和 Twitter Cards
title = "Doごみ箱"
# 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
description = "Doごみ箱2.1"
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = ["/img/dodola.png"]
keyword = ["Doごみ箱", "DoIt", "Hugo", "DODOLA"]

enablePWA = false
# 缓存图片
cacheRemoteImages = false
optimizeImages = true
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
recentlyUpdated = true


# 页面头部导航栏配置
[params.header]
themeChangeMode = "select"
# 桌面端导航栏模式 ["fixed", "normal", "auto"]
desktopMode = "fixed"
# 移动端导航栏模式 ["fixed", "normal", "auto"]
mobileMode = "auto"
#  页面头部导航栏标题配置
[params.header.title]
# LOGO 的 URL
# logo = "/logo.png"
# 标题名称
name = "Doごみ箱2.1"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
# pre='<i class="fa-solid fa-dumpster"></i>'
pre = "🗑️"
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
# post = "<i class='fa-solid fa-paw fa-rotate-by' style='--fa-rotate-angle: 30deg;'></i>"
post = "🐾"
#  是否为标题显示打字机动画
typeit = false

# 页面底部信息配置
[params.footer]
enable = true
#  自定义内容 (支持 HTML 格式)
custom = ''
#  是否显示 Hugo 和主题信息
hugo = true
#  是否显示版权信息
copyright = true
#  是否显示作者
author = true
# 网站创立年份
since = 2023
# ICP 备案信息，仅在中国使用 (支持 HTML 格式)
icp = '<p class="beian"><img class="beian-icon" src="/img/icons/govbeian.png"><a class="gov" href="https://beian.mps.gov.cn/#/query/webSearch?code=33010902003733" rel="noreferrer" title="浙公网安备33010902003733" target="_blank">浙公网安备33010902003733</a><a class="icp" href="https://beian.miit.gov.cn/#/Integrated/index" target="_blank" title="浙ICP备2023048052号-1">浙ICP备2023048052号-1</a></p>'
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

#  Section (所有文章) 页面配置
[params.section]
# section 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10
days = 30
maxCount = 10

#  List (目录或标签) 页面配置
[params.list]
# list 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

#  应用图标配置
[params.app]
# 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
title = "Doごみ箱-一只小菜鸡的Blog"
# 是否隐藏网站图标资源链接
noFavicon = false
# 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
svgFavicon = "/logo.svg"
# Android 浏览器主题色
themeColor = "#ffffff"
# Safari 图标颜色
iconColor = "#5bbad5"
# Windows v8-10磁贴颜色
tileColor = "#da532c"

#  搜索配置
[params.search]
enable = true
# 搜索引擎的类型 ["lunr", "algolia"]
type = "fuse"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = "搜索本站内容( •̀ ω •́ )y"
#  最大结果数目
maxResultLength = 10
#  结果内容片段长度
snippetLength = 50
#  搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
#  是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false
[params.search.algolia]
index = ""
appID = ""
searchKey = ""
[params.search.fuse]
isCaseSensitive = false
minMatchCharLength = 2
findAllMatches = false
location = 0
threshold = 0.3
distance = 100
ignoreLocation = false
useExtendedSearch = false
ignoreFieldNorm = false

[params.image]
cacheRemote = false
optimize = true

# 主页配置
[params.home]
#  RSS 文章数目
rss = 10
# 主页个人信息
[params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = ""
# 主页显示头像的 URL
avatarURL = "/img/dodola.png"
#  主页显示的网站标题 (支持 HTML 格式)
title = "一只小菜鸡的Blog"
# 主页显示的网站副标题 (允许 HTML 格式)
subtitle = "Doごみ箱2.1"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
#  免责声明 (支持 HTML 格式)
disclaimer = ""
# 主页文章列表
[params.home.posts]
enable = true
# 主页每页显示文章数量
paginate = 6
#  被 params.page 中的 hiddenFromHomePage 替代
# 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
defaultHiddenFromHomePage = false

# 作者的社交信息设置
[params.social]
GitHub = "Florae006"
Linkedin = ""
# Twitter = ""
# Instagram = ""
# Facebook = ""
# Telegram = ""
Medium = ""
Gitlab = ""
Youtubelegacy = ""
Youtubecustom = ""
Youtubechannel = ""
Tumblr = ""
Quora = ""
Keybase = ""
Pinterest = ""
Reddit = ""
Codepen = "Florae006"
FreeCodeCamp = ""
Bitbucket = ""
Stackoverflow = ""
Weibo = ""
Odnoklassniki = ""
VK = ""
Flickr = ""
Xing = ""
Snapchat = ""
Soundcloud = ""
Spotify = ""
Bandcamp = ""
Paypal = ""
Fivehundredpx = ""
Mix = ""
Goodreads = ""
Lastfm = ""
Foursquare = ""
Hackernews = ""
Kickstarter = ""
Patreon = ""
Steam = "1435978954"
Twitch = ""
Strava = ""
Skype = ""
Whatsapp = ""
Zhihu = "74-2-17-80-21"
Douban = "253563633"
Angellist = ""
Slidershare = ""
Jsfiddle = ""
Deviantart = ""
Behance = ""
Dribbble = ""
Wordpress = ""
Vine = ""
Googlescholar = ""
Researchgate = ""
Mastodon = ""
Thingiverse = ""
Devto = ""
Gitea = ""
XMPP = ""
Matrix = ""
Bilibili = "219659631"
Discord = ""
DiscordInvite = ""
Lichess = ""
ORCID = ""
Pleroma = ""
Kaggle = ""
MediaWiki = ""
Plume = ""
HackTheBox = ""
RootMe = ""
Phone = "17543809322"
Email = "chenflora124@gmail.com"
RSS = true                       # 
Liberapay = ""
Ko-Fi = ""
BuyMeACoffee = ""
Linktree = ""
# QQ = "2407445307"
# QQGroup = ""
#  文章页面全局配置
[params.page]
#  是否在主页隐藏一篇文章
hiddenFromHomePage = false
#  是否在搜索结果中隐藏一篇文章
hiddenFromSearch = false
#  是否使用 twemoji
twemoji = false
# 是否使用 lightgallery
lightgallery = false
#  是否使用 ruby 扩展语法
ruby = true
#  是否使用 fraction 扩展语法
fraction = true
#  是否使用 fontawesome 扩展语法
fontawesome = true
# 是否在文章页面显示原始 Markdown 文档链接
linkToMarkdown = true
linkToEdit = false
linkToSource = false
#  是否在 RSS 中显示全文内容
rssFullText = false
seriesNavigation = true
seriesNavigationText = "相关系列"
seriesNavigationPosition = "bottom"
# 是否启用最后修改时间
enableLastMod = true
# 是否启用字数统计
enableWordCount = true
# 是否启用阅读时间估计
enableReadingTime = true
# 是否启用文章更新提醒
[params.page.outdatedArticleReminder]
enable = true
# 如果文章最后更新于 90 天之前，显示提醒
reminder = 90
# 如果文章最后更新于 180 天之前，显示警告
warning = 180
#  目录配置
[params.page.toc]
# 是否使用目录
enable = true
#  是否保持使用文章前面的静态目录
keepStatic = false
# 是否使侧边目录自动折叠展开
auto = true
#  代码配置
[params.page.code]
# 是否显示代码块的复制按钮
copy = true
# 默认展开显示的代码行数
maxShownLines = 50
#  KaTeX 数学公式
[params.page.table]
# 是否开启表格排序
sort = true
[params.page.math]
enable = true
#  默认行内定界符是 $ ... $ 和 \( ... \)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
#  默认块定界符是 $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} 和一些其它的函数
blockLeftDelimiter = ""
blockRightDelimiter = ""
# KaTeX 插件 copy_tex
copyTex = true
# KaTeX 插件 mhchem
mhchem = true
# 使用 MathJax 代替 KaTeX
mathjax = false
#  Mapbox GL JS 配置
[params.page.mapbox]
# Mapbox GL JS 的 access token
accessToken = ""
# 浅色主题的地图样式
lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
# 深色主题的地图样式
darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
# 是否添加 NavigationControl
navigation = true
# 是否添加 GeolocateControl
geolocate = true
# 是否添加 ScaleControl
scale = true
# 是否添加 FullscreenControl
fullscreen = true
#  文章页面的分享信息设置
[params.page.share]
enable = true
Twitter = true
Facebook = true
Linkedin = false
Whatsapp = false
Pinterest = false
Tumblr = false
HackerNews = true
Reddit = false
VK = false
Buffer = false
Xing = false
Line = true
Instapaper = false
Pocket = false
Flipboard = false
Weibo = true
Blogger = false
Baidu = true
Odnoklassniki = false
Evernote = false
Skype = false
Trello = false
Mix = false
[params.page.instantpage]
enable = true
# 是否使用 Instant.page 预加载
prefetch = false
# 是否使用 Instant.page 预加载
prerender = false

#  评论系统设置
[params.page.comment]
enable = true
# Disqus 评论系统设置
[params.page.comment.disqus]
# 
enable = false
# Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
shortname = ""
# Gitalk 评论系统设置
[params.page.comment.gitalk]
# 
enable = false
owner = ""
repo = ""
clientId = ""
clientSecret = ""
# Valine 评论系统设置
[params.page.comment.valine]
enable = false
appId = ""
appKey = ""
placeholder = ""
avatar = "mp"
meta = ""
pageSize = 10
# 为空时自动适配当前主题 i18n 配置
lang = ""
visitor = true
recordIP = true
highlight = true
enableQQ = false
serverURLs = ""
#  emoji 数据文件名称, 默认是 "google.yml"
# ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
# 位于 "themes/LoveIt/assets/lib/valine/emoji/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件:
# "assets/lib/valine/emoji/"
emoji = ""
# Facebook 评论系统设置
[params.page.comment.facebook]
enable = false
width = "100%"
numPosts = 10
appId = ""
# 为空时自动适配当前主题 i18n 配置
languageCode = "zh_CN"
#  Telegram Comments 评论系统设置
[params.page.comment.telegram]
enable = false
siteID = ""
limit = 5
height = ""
color = ""
colorful = true
dislikes = false
outlined = false
#  Commento 评论系统设置
[params.page.comment.commento]
enable = false
#  utterances 评论系统设置
[params.page.comment.utterances]
enable = false
# owner/repo
repo = ""
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
darkTheme = "github-dark"
# giscus comment 评论系统设置 (https://giscus.app/zh-CN)
[params.page.comment.giscus]
# 你可以参考官方文档来使用下列配置
enable = false
repo = ""
repoId = ""
category = "Announcements"
categoryId = ""
# 为空时自动适配当前主题 i18n 配置
lang = ""
mapping = "pathname"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lazyLoading = false
lightTheme = "light"
darkTheme = "dark"
# Waline 评论系统设置
[params.page.comment.waline]
# DoIt 更改 | 0.2.14
enable = false
serverURL = ""
pageview = true
comment = true
# emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
# meta = ['nick', 'mail', 'link']
# requiredMeta = []
# login = 'enable'
# wordLimit = 0
# pageSize = 10
# imageUploader = false
# highlighter = false
# texRenderer = false

# DoIt 新增 | 0.2.12 Twikoo 评论系统设置
[params.page.comment.twikoo]
# version = "1.6.32"
enable = true
envId = "https://twikoo.dodolalorc.cn/"
region = "ap-shanghai"
path = "window.TWIKOO_MAGIC_PATH || window.location.pathname"
pageSize = 10
lang = "zh-CN"
el = "#twikoo"
cloudbase = false
visitor = true
commentCount = true
# DoIt 新增 | 0.2.12 Vssue 评论系统设置
[params.page.comment.vssue]
enable = false
platform = ""     # ("bitbucket", "gitea", "gitee", "github", "gitlab")
owner = ""
repo = ""
clientId = ""
clientSecret = ""
# DoIt 新增 | 0.2.13 Remark42 评论系统设置
[params.page.comment.remark42]
enable = false
host = ""
site_id = ""
max_shown_comments = 15
show_email_subscription = true
simple_view = false
# artalk 评论系统设置
[params.page.comment.artalk]
enable = false
server = ""
site = ""
lite = false
katex = false
lightbox = false
pageview = true
commentCount = true
#  第三方库配置
[params.page.library]
[params.page.library.css]
# someCSS = "some.css"
# DoIt 新增 | 0.2.14 更多第三方库配置
# [params.page.library.css.someOtherCSS]
#   src = "someOther.css"
#   defer = true
#   attr = "customAttribute"
# 位于 "assets/"
# 或者
# someCSS = "https://cdn.example.com/some.css"
[params.page.library.js]
# someJavaScript = "some.js"
# DoIt 新增 | 0.2.14 更多第三方库配置
# [params.page.library.js.someOtherJavaScript]
#   src = "https://cdn.jsdelivr.net/npm/twikoo@1.6.36/dist/twikoo.all.min.js"
#   integrity = "sha384-4KfOjEinLSkv1i1J8TzlkC/RTnuiLoR1OLerVgjEKoH5djYtbf7mzEFsz9p3nfuA" 
#   crossorigin = "anonymous"
#   defer = false
#   async = true
#   attr = "customAttribute"
# 位于 "assets/"
# 或者
# twikooJS = "https://cdn.jsdelivr.net/npm/twikoo@1.6.36/dist/twikoo.all.min.js"
#  页面 SEO 配置
[params.page.seo]
# 图片 URL
images = []
# 出版者信息
[params.page.seo.publisher]
name = "DODOLA"
logoUrl = ""
# DoIt 新增 | 0.2.14 相关文章推荐配置
[params.page.related]
enable = true
count = 5

[params.sponsor]
enable = false
bio = "如果你觉得这篇文章对你有所帮助，欢迎赞赏~"
link = "https://www.buymeacoffee.com" # 你的赞赏页面的地址
custom = ""                           # 自定义 HTML
# 二维码图片地址
# qrcode = ""
# # 二维码提示信息
# qrcodeTitle = "微信赞赏"
# # 二维码提示信息
# qrcodeSubtitle = "微信扫一扫赞赏"

#  TypeIt 配置
[params.typeit]
# 每一步的打字速度 (单位是毫秒)
speed = 100
# 光标的闪烁速度 (单位是毫秒)
cursorSpeed = 1000
# 光标的字符 (支持 HTML 格式)
cursorChar = "|"
# 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
duration = -1

# 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
google = ""
bing = ""
yandex = ""
pinterest = ""
baidu = ""

#  网站 SEO 配置
[params.seo]
# 图片 URL
image = ""
# 缩略图 URL
thumbnailUrl = ""

alternateName = ["Doごみ箱", "flora", "dodola"]

#  网站分析配置
[params.analytics]
enable = false
# Google Analytics
[params.analytics.google]
id = "G-4XWE9N9JQK"
# 是否匿名化用户 IP
anonymizeIP = true
# Fathom Analytics
[params.analytics.fathom]
id = ""
# 自行托管追踪器时的主机路径
server = ""
# Plausible Analytics
[params.analytics.plausible]
dataDomain = ""
# Yandex Metrica
[params.analytics.yandexMetrica]
id = ""

# 添加不蒜子计数
[params.busuanzi]
enable = true
# 是否开启全站独立访客数
site_uv = true
# 全站独立访客数前的图标或提示语
site_uv_pre = '<i class="fa fa-user"></i>'
# 全站独立访客数后的图标或提示语
site_uv_post = ''
# 是否开启全站浏览量
site_pv = true
# 全站浏览量前的图标或提示语
site_pv_pre = '<i class="fa fa-eye"></i>'
# 全站浏览量后的图标或提示语
site_pv_post = ''
# 是否开启单页浏览量
page_pv = true
# 单页浏览量前的图标或提示语
page_pv_pre = '<i class="far fa-eye fa-fw"></i>'
# 单页浏览量后的图标或提示语
page_pv_post = ''


#  Cookie 许可配置
# [params.cookieconsent]
#   enable = true
#   # 用于 Cookie 许可横幅的文本字符串
#   [params.cookieconsent.content]
#     message = ""
#     dismiss = ""
#     link = ""

#  第三方库文件的 CDN 设置
[params.cdn]
# CDN 数据文件名称, 默认不启用
# ["jsdelivr.yml"]
# 位于 "themes/LoveIt/assets/data/cdn/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件:
# "assets/data/cdn/"
data = ""

#  兼容性设置
[params.compatibility]
# 是否使用 Polyfill.io 来兼容旧式浏览器
polyfill = false
# 是否使用 object-fit-images 来兼容旧式浏览器
objectFit = false

# Hugo 解析文档的配置
[markup]
# 语法高亮设置
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
# false 是必要的设置
# (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
# Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
# 是否在文档中直接使用 HTML 标签
unsafe = true
# 目录设置
[markup.tableOfContents]
startLevel = 2
endLevel = 6

# 作者配置
[author]
name = "DODOLA"
email = "flora_chen2021@163.com"
link = "http://dodolalorc.cn/"
avatar = "/img/dodola.png"
gravatarEmail = ""

# 网站地图配置
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks 配置
[Permalinks]
# posts = ":year/:month/:filename"
# posts = ":filename"
posts = "/posts/:filename"

# 隐私信息配置
[privacy]
#  Google Analytics 相关隐私 (被 params.analytics.google 替代)
[privacy.googleAnalytics]
# ...
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
mediaType = "text/plain"
isPlainText = true
isHTML = false

# 用于 Hugo 输出文档的设置
[outputs]
# 
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML", "RSS"]
# taxonomyTerm = ["HTML"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"
