name: Deploy

# 触发条件
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: sebastianjnuwu/ssh-action-deploy@v3
      with:
        KEY: ${{ secrets.HUGO_DEPLOY_PRI }}
        IP: ${{ secrets.REMOTE_HOST }}
        USER: ${{ secrets.REMOTE_USER }}
        FOLDER: ${{ secrets.REMOTE_TARGET }}
        RUN: ls -a; pwd
