name: Deploy

# 触发条件
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build --if-present
      - shell: bash
        run: |
          echo "${{ secrets.HUGO_DEPLOY_PRI }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.HUGO_DEPLOY_PRI }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: 
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: 
          SCRIPT_BEFORE:
          SCRIPT_AFTER: