name: Deploy

# 触发条件
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    # - name: Install npm dependencies
    #   run: npm install
    # - name: Run build task
    #   run: npm run build --if-present

    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v5.0.3
      with:
        SSH_PRIVATE_KEY: ${{ secrets.HUGO_DEPLOY_PRI }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: ""
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        # EXCLUDE: "/dist/, /node_modules/"
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          whoami
          ls -al
          echo $RSYNC_STDOUT
      # uses: sebastianjnuwu/ssh-action-deploy@v3
      # with:
      #   KEY: ${{ secrets.HUGO_DEPLOY_PRI }}
      #   IP: ${{ secrets.REMOTE_HOST }}
      #   USER: ${{ secrets.REMOTE_USER }}
      #   FOLDER: ${{ secrets.REMOTE_TARGET }}
      #   RUN: ls -a; pwd
